from snakemake.utils import min_version
import os

min_version("8.11.6")  # Docker syntax changes in recent updates.


configfile: "workflow/config.yaml"

# Import root directory
ROOT_DIR = config['paths']['ROOT_DIR']

# to change paths
os.environ["SNAKEMAKE_EXECUTION"] = "1"

# Specify the container to use for this rule
container: "docker://residual233/ipynb-execution:latest"

rule all:
    input:
        os.path.join(ROOT_DIR, "02-Data_Curation/unified-curated.db"),
        os.path.join(ROOT_DIR, "03-EDA/AA-makeup.pdf"),
        os.path.join(ROOT_DIR, "03-EDA/seqLengthDistribution.pdf"),
        os.path.join(ROOT_DIR, "unified-final.db"),
        os.path.join(ROOT_DIR, "05-logistic_regression/roc.pdf"),
        os.path.join(ROOT_DIR, "06-SVM/output.pdf"),
        os.path.join(ROOT_DIR, "07-KNN/final_pcaPN_four.png"),
        os.path.join(ROOT_DIR, "08-RFC/roc.png"),
        os.path.join(ROOT_DIR, "08-RFC/roc.png")



rule curation:
    input:
        os.path.join(ROOT_DIR, "01-Data_Extraction/new_data_pos_neg.csv")
    output:
        os.path.join(ROOT_DIR, "02-Data_Curation/unified-curated.db")
    notebook:
        os.path.join(ROOT_DIR, "02-Data_Curation/DB_curation.ipynb")


rule EDA:
    input:
        os.path.join(ROOT_DIR, "02-Data_Curation/unified-curated.db")
    output:
        os.path.join(ROOT_DIR, "03-EDA/AA-makeup.pdf"),
        os.path.join(ROOT_DIR, "03-EDA/seqLengthDistribution.pdf")
    notebook:
        os.path.join(ROOT_DIR, "03-EDA/DataExploration.ipynb")

rule calculate_descriptors:
    input:
        os.path.join(ROOT_DIR, "02-Data_Curation/unified-curated.db")
    output:
        os.path.join(ROOT_DIR, "unified-final.db")
    script:
        os.path.join(ROOT_DIR, "04-Data_calculate_Descriptors/CD2.py")

rule logistic_regression:
    input:
        os.path.join(ROOT_DIR, "unified-final.db")
    output:
        os.path.join(ROOT_DIR, "05-logistic_regression/roc.pdf")
    notebook:
        os.path.join(ROOT_DIR, "05-logistic_regression/logistic regression.ipynb")


rule svm_kernel:
    input:
        os.path.join(ROOT_DIR, "unified-final.db")
    output:
        os.path.join(ROOT_DIR, "06-SVM/output.pdf")
    notebook:
        os.path.join(ROOT_DIR, "06-SVM/SVM kernelPCA.ipynb")

rule svm_model:
    input:
        os.path.join(ROOT_DIR, "unified-final.db")
    output:
        os.path.join(ROOT_DIR, "06-SVM/roc.pdf")
    notebook:
        os.path.join(ROOT_DIR, "06-SVM/SVM model.ipynb")

rule knn:
    input:
        os.path.join(ROOT_DIR, "unified-final.db")
    output:
        os.path.join(ROOT_DIR, "07-KNN/final_pcaPN_four.png")
    notebook:
        os.path.join(ROOT_DIR, "07-KNN/knn.ipynb")

rule rfc:
    input:
        os.path.join(ROOT_DIR, "unified-final.db")
    output:
        os.path.join(ROOT_DIR, "08-RFC/roc.png")
    notebook:
        os.path.join(ROOT_DIR, "08-RFC/randomforest.ipynb")


